import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // jo weights chahiye
  subsets: ["latin"], // language subset
  variable: "--font-poppins", // optional CSS variable
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
